{ ... }:
{
  imports = [
    ../../programs/chromium
    ../../programs/xarchiver
    ../../programs/obs
    ../../programs/minecraft
    ../../programs/androidStudio
    ../../programs/godot
    ../../programs/tuckr
    ../../programs/waybar
    ../../programs/gnupg
    ../../programs/steam
    ../../programs/thunar
    ../../programs/neovim
    ../../programs/firefox
    ../../programs/zsh
    ../../programs/starship
    ../../programs/direnv
    ../../programs/inputMethod
    ../../programs/keepassxc
    ../../programs/kicad
    ../../programs/ripgrep
    ../../programs/swayimg
    ../../programs/yazi
    ../../programs/devenv
    ../../programs/git
    ../../programs/freecad
    ../../programs/telegram
    ../../programs/drawio
    ../../programs/blender
    ../../programs/ghostty
    ../../programs/fuzzel
    ../../programs/niri
    ../../programs/light
    ../../programs/krita
  ];
}
